/*
 * A.TORRES
 *
 * C#.NET LAB: Grand Circus Trip Planner
 */
CREATE DATABASE TripPlanner;
go

use TripPlanner

CREATE TABLE [User] (
	UserId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PhoneNumber NVARCHAR(15) NOT NULL,
	[Address] NVARCHAR(40) NOT NULL,
	DOB DATE NOT NULL
);
go
CREATE TABLE Passport(
	PassportId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PassportNumber NVARCHAR(20) NOT NULL,
	ExpirationDate DATE NOT NULL,
	[Address] NVARCHAR(40) NOT NULL
);
go
ALTER TABLE [User] ADD PassportId INT FOREIGN KEY REFERENCES Passport(PassportId);
ALTER TABLE Passport ADD UserId INT FOREIGN KEY REFERENCES [User](UserId);
GO
CREATE TABLE Trip (
	TripId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Budget DECIMAL NOT NULL,
	StartDest NVARCHAR(50) NOT NULL,
	EndDest NVARCHAR(50) NOT NULL,
	TravelMode NVARCHAR(10) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL
);
go
ALTER TABLE Trip ADD UserId INT FOREIGN KEY REFERENCES [User](UserId);
go
CREATE TABLE Hotel (
	HotelId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CheckInDate DATE NOT NULL,
	CheckOutDate DATE NOT NULL,
	ContactPhone NVARCHAR(15) NOT NULL,
	ContactAddress NVARCHAR(40) NOT NULL,
	CostPerNight DECIMAL NOT NULL
);
go
CREATE TABLE TripHotel (
	TripHotelId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL
);
go
ALTER TABLE TripHotel ADD TripId INT FOREIGN KEY REFERENCES Trip(TripId);
go
ALTER TABLE TripHotel ADD HotelId INT FOREIGN KEY REFERENCES Hotel(HotelId);
go
